# SSH Log Collector Configuration File
# Edit this file to configure your servers and log directories

servers:
  # Ví dụ cấu hình server sử dụng username/password
  - name: "My Linux Server"
    host: "192.168.1.100"        # Thay bằng IP hoặc hostname của server
    port: 22                     # Cổng SSH (thường là 22)
    username: "your_username"    # Tên đăng nhập SSH
    password: "your_password"    # Mật khẩu SSH
    key_file: null               # Đặt null khi dùng password
    passphrase: null             # Không cần khi dùng password
    timeout: 30                  # Thời gian chờ kết nối (giây)

directories:
  # Cấu hình các thư mục log cần thu thập
  - name: "System Logs"
    path: "/var/log"                 # Đường dẫn thư mục trên server
    server: "My Linux Server"        # Tên server (phải khớp với tên ở trên)
    file_pattern: "*.log"            # Mẫu file cần lấy (*.log = tất cả file .log)
    recursive: false                 # false = chỉ thư mục hiện tại, true = bao gồm thư mục con

  - name: "Application Logs"
    path: "/var/log/myapp"
    server: "My Linux Server"
    file_pattern: "*.log"
    recursive: true                  # Tìm trong cả thư mục con

  - name: "Nginx Logs"
    path: "/var/log/nginx"
    server: "My Linux Server"
    file_pattern: "*.log*"           # Bao gồm cả file nén (.log.gz)
    recursive: false

settings:
  # Default directory to download files
  default_download_path: "./downloads"
  
  # Maximum number of concurrent file transfers (tối ưu cho file lớn 40-50MB)
  max_concurrent_transfers: 2
  
  # Number of retry attempts for failed operations (tăng để xử lý lỗi mạng)
  retry_attempts: 5
  
  # Connection timeout in seconds (tăng cho kết nối ổn định hơn)
  connection_timeout: 60
  
  # SSH specific settings
  ssh_banner_timeout: 60
  ssh_auth_timeout: 60
